/**
 * \file src/io/xml_loader_v2.hpp
 * \brief Public API for XML loader v2 import and export routines.
 */

#ifndef XML_LOADER_V2_HPP
#define XML_LOADER_V2_HPP

#include <QDomDocument>
#include <QStack>

#include "graph.hpp"

/**
 *  \brief Load legacy files
 *
 *  Knot XML files v2 are for Knotter 0.5 - 0.8
 *
 *  This will also load knot v1 files ( generated by Knotter 0.1 - 0.4 ) with
 *  minor style information losses
 */
class XML_Loader_v2
{
   private:
    static const int supported_version = 2;

    QDomDocument xml;
    QStack<QDomElement> current_elements;
    int version;
    QMap<QString, Node*> node_ids;

   public:
    bool load(QIODevice* input);

    void get_graph(Graph& kv);

    Node* register_node(QString id);

    bool enter(QString name);

    QPen get_pen(QString name, QPen default_value);

    Node_Style get_cusp(QString name);

    void leave();

    static bool supports_version(int v) { return v > 0 && v <= supported_version; }
};
#endif  // XML_LOADER_V2_HPP
